[package]
name = "thebes-example-xray-backend"
version = "0.1.0"
description = "Backend for the Thebes Protocol medical-imaging (X-ray) example."
license = "Apache-2.0"

[dependencies]
core = "2.5.0"
thebes-lib = "./thebes-lib"

[toolchain]
moc = "1.4.1"
